apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: default
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: 9001
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: nicholasjackson/fake-service:v0.25.1
          imagePullPolicy: IfNotPresent
          env:
            - name: NAME
              value: "frontend"
            - name: MESSAGE
              value: "Hello from frontend"
            - name: LOG_LEVEL
              value: "debug"
            - name: LISTEN_ADDR
              value: "127.0.0.1:9001"
            - name: UPSTREAM_URIS
              value: "http://backend.virtual.default.ns.bar.ap.consul:9001"
          ports:
            - containerPort: 9001
