apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend-to-backend
spec:
  destination:
    name: backend
  sources:
    - name: frontend
      partition: foo
      action: allow
